const callbackData = [ {
  id: 1,
  callbackDateTime: '',
  name: 'Martha Henderson',
  phoneNumber: '(049)396-5777',
  status: 'Active',
  campaign: 'OLIVETN2',
  lastCallDateTime: '',
  length: 0.10,
  inOut: 'Out-Manual',
  alt: 'Manual',
  hangup: 'Agent',
  timezone: -4.00,
}, {
  id: 2,
  callbackDateTime: '',
  name: 'Rachael Cunningham',
  phoneNumber: '(958)205-7093',
  status: 'Active',
  campaign: 'OLIVETN2',
  lastCallDateTime: '',
  length: 0.10,
  inOut: 'Out-Manual',
  alt: 'Manual',
  hangup: 'Agent',
  timezone: -4.00,
}, {
  id: 3,
  callbackDateTime: '',
  name: 'Jessica Mendoza',
  phoneNumber: '(288)608-2640',
  status: 'Active',
  campaign: 'OLIVETN2',
  lastCallDateTime: '',
  length: 0.10,
  inOut: 'Out-Manual',
  alt: 'Manual',
  hangup: 'Agent',
  timezone: -4.01,
},

]

// eslint-disable-next-line import/prefer-default-export
export { callbackData }
