export const ERRORS = {
  UNAUTHORIZED: 'unauthorized',
  FORBIDDEN: 'forbidden',
  NOT_FOUND: 'notFound',
  METHOD_NOT_ALLOWED: 'methodNotAllowed',
  BAD_DATA: 'badData',
  BAD_REQUEST: 'badRequest',
  INTERNAL: 'internal',
  SERVER_ERROR: 'serverError',
  SERVER_UNAVAILABLE: 'serverUnavailable'
}

export const APP_ERROR_CODES = {
  EMAIL_NOT_REGISTERED: 'Email not registered!',
  EMAIL_NOT_VERIFIED: 'Email not verified!',
  INCORRECT_PASSWORD: 'Incorrect Password!',
  EMAIL_NOT_AVAILABLE: 'Email not available!'
}

export const MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  SERVER_ERROR: 'An error occurred while processing your request. Please try again later.',
  CLIENT_NOT_FOUND: 'Client does not exist for this user, Please complete step 1 First',
  UNAUTHORIZED: 'You don\'t have permission to access this page',
  FLOW_NOT_EXIST: 'Flow does not exist',
  FLOW_PAGE_NOT_EXIST: 'Flow page does not exist',
  FLOW_FIELD_NOT_EXIST: 'Flow field does not exist',
  TOPIC_NOT_EXIST: 'Forum topic does not exist',
  CHANNEL_NOT_EXIST: 'Forum channel does not exist',
  CATEGORY_NOT_EXIST: 'Category does not exist',
  JOB_NOT_EXIST: 'Job does not exist',
  TOPIC_COMMENT_NOT_EXIST: 'Forum topic comment does not exist',
  COMMENT_DELETED_SUCCESSFULLY: 'Topic comment successfully deleted',
  UNAUTHORIZED_MSG: 'You don\'t have permission to perform this action!',
  INVALID_IMAGE_FILE: 'File is not valid image file!',
  INVALID_IMAGE_FILE_SIZE: 'File size should not be greater than 1 MB!',
  INVALID_VIDEO_FILE: 'File is not valid video file!',
  INVALID_VIDEO_FILE_SIZE: 'File size should not be greater than 100 MB!',
  INVALID_AUDIO_FILE: 'File is not valid audio file!',
  INVALID_AUDIO_FILE_SIZE: 'File size should not be greater than 100 MB!',
  IPFS_FILE_UPLOAD_ERROR: 'Error occured while uploadind file on IPFS!',
  POST_STATUS_NOT_EXIST: 'Post status does not exist',
  STATUS_DELETED_SUCCESSFULLY: 'Post status successfully deleted',
  LIKE_ERROR_MESSAGE: 'You have already liked this post!',
  UNLIKE_ERROR_MESSAGE: 'You have already unliked this post!',
  COMMENT_UPDATED_SUCCESSFULLY: 'Topic comment successfully updated',
  POST_COMMENT_DELETED_SUCCESSFULLY: 'Post comment successfully deleted',
  POST_COMMENT_UPDATED_SUCCESSFULLY: 'Post comment successfully updated',
  PHONE_NUMBER_IS_INVALID: 'Phone number is invalid',
  EMAIL_ALREADY_REGISTERED: 'Email already registered! Please login',
  FORUM_GROUP_NOT_EXIST: 'Forum group does not exist or deleted',
  DATA_NOT_FOUND: 'Requested data not found!',
  CLIENT_NOT_EXIST: 'Client does not exist',
  REVIEW_ALREADY_ADDED: 'Review Already Added',
  AGENT_ALREADY_INVITED: 'Agent already invited for this job post!',
  JOB_ALREADY_APPLIED: 'This agent has already applied to this job',
  JOB_APPLICATION_NOT_EXIST: 'Application does not exist!',
  JOB_APPLICATION_NOT_UPDATED: 'Application not updated!',
  COURSE_NOT_FOUND: 'Course not found!',
  CANNOT_EDIT_COURSE: 'You can\'t edit this course!',
  USER_ALREADY_ENROLLED: 'User already enrolled to this course',
  CLIENT_NAME_ALREADY_EXISTS: 'Company name already exists',
  CANNOT_FOLLOW: 'You cannot follow this user',
  CANNOT_BLOCK: 'You cannot block this user'
}
