export { PeopleAddNewCourseService } from './createCourse'
export { PeopleGetAllCoursesService } from './getAllCourses'
export { PeopleGetCourseService } from './getCourse'
export { PeopleUpdateCourseService } from './updateCourse'
export { PeopleGetAllViewCoursesService } from './getAllViewCourses'
