const questions = [
  {
    id: 1,
    questionType: 'multiple',
    questionText: 'Sample question 1',
    answerText: '',
    options: [
      {
        id: 1,
        value: 'option a',
      },
      {
        id: 2,
        value: 'option b',
      },
      {
        id: 3,
        value: 'option c',
      },
    ],
    correctOptions: null,
    correctOption: 2,
    userAnswer: 1,
    userOptions: null,
    isCorrect: false,
    scale: null,
  },
  {
    id: 2,
    questionType: 'text',
    questionText: 'Sample question 2',
    answerText: 'Correct answer',
    options: null,
    correctOptions: null,
    correctOption: null,
    userAnswer: 'wrong answer',
    userOptions: null,
    isCorrect: false,
    scale: null,
  },
  {
    id: 3,
    questionType: 'paragraph',
    questionText: 'Sample question 3',
    answerText: 'Correct answer',
    options: null,
    correctOptions: null,
    correctOption: null,
    userAnswer: 'Correct answer',
    userOptions: null,
    isCorrect: true,
    scale: null,
  },
  {
    id: 4,
    questionType: 'checkbox',
    questionText: 'Sample question 4',
    answerText: '',
    options: [
      {
        id: 1,
        value: 'option a',
      },
      {
        id: 2,
        value: 'option b',
      },
      {
        id: 3,
        value: 'option c',
      },
    ],
    correctOptions: [ 1, 2 ],
    correctOption: null,
    userAnswer: null,
    userOptions: [ 1, 3 ],
    isCorrect: false,
    scale: null,
  },
  {
    id: 5,
    questionType: 'scale',
    questionText: 'Sample question 5',
    answerText: 25,
    options: null,
    correctOptions: null,
    correctOption: null,
    userAnswer: 20,
    userOptions: null,
    isCorrect: false,
    scale: {
      minRange: -30,
      maxRange: 30,
    },
  },
  {
    id: 6,
    questionType: 'date',
    questionText: 'Sample question 6',
    answerText: '{"date":"2021-11-04","time":"23:01"}',
    options: null,
    correctOptions: null,
    correctOption: null,
    userAnswer: '{"date":"2021-11-05","time":"23:01"}',
    userOptions: null,
    isCorrect: false,
    scale: null,
  },
]

// eslint-disable-next-line import/prefer-default-export
export { questions }
